language: python

install:
  - "pip install --pre -r requirements.txt"
  - "pip install python-coveralls"

python:
  - "3.4"
  - "3.2"

script:
  - py.test --cov framework framework/tests/

after_success:
  - coveralls